# REST API

### Root Test
GET http://localhost:3000/

### About
GET http://localhost:3000/about

### Get All Profile
GET http://localhost:3000/profile

### Create New Profile
POST http://localhost:3000/profile
Content-Type: application/json

{
  "username": "yaiba2",
  "password": "1234",
  "mobile": "0933851499",
  "cardid": "1233857881744"
}

### Get Profile by ID
GET http://localhost:3000/profile/7645b518-749d-4c18-a2e3-93eb3a8d3a49
